import os
import time
import logging
import json
from dotenv import load_dotenv
from langchain_nvidia_ai_endpoints import ChatNVIDIA
from langchain.agents import create_agent
from langchain_core.messages import HumanMessage, ToolMessage, AIMessage
from tools import web_search, scrape_url

# --- Layer 1: Setup Advanced Diagnostics ---
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="langchain_nvidia_ai_endpoints")

logging.basicConfig(
    level=logging.INFO,
    format='[%(asctime)s] [%(levelname)s] [DIAGNOSTIC] - %(message)s'
)
logger = logging.getLogger("LangGraphDiagnostics")

def format_separator(title):
    return f"\n{'='*25} {title} {'='*25}\n"

def run_diagnostic():
    print(format_separator("LAYER 1: ENVIRONMENT & KEY VALIDATION"))
    load_dotenv()
    api_key = os.getenv("NVIDIA_API_KEY")
    tavily_key = os.getenv("TAVILY_API_KEY")
    
    logger.info(f"NVIDIA API Key exists: {api_key is not None} (Length: {len(api_key) if api_key else 0})")
    logger.info(f"Tavily API Key exists: {tavily_key is not None} (Length: {len(tavily_key) if tavily_key else 0})")
    
    if not api_key:
        logger.error("CRITICAL: NVIDIA_API_KEY is missing from environment. Aborting.")
        return

    print(format_separator("LAYER 2: LLM & AGENT GRAPH COMPILATION"))
    model_name = "nvidia/nemotron-3.5-lightning-30b-a3b"
    logger.info(f"Configuring ChatNVIDIA with model: '{model_name}'")
    
    try:
        # 1. Initialize LLM with Thinking Enabled
        llm = ChatNVIDIA(
            model=model_name,
            api_key=api_key,
            temperature=0.7,
            max_completion_tokens=4000, 
            timeout=120,  # Prevent ReadTimeout during long reasoning/thinking steps
            model_kwargs={
                "chat_template_kwargs": {"enable_thinking": True},
                "reasoning_budget": 2048
            }
        )
        logger.info("ChatNVIDIA instance created.")
        
        # 2. Compile LangGraph Agent using factory.create_agent (same as codebase)
        logger.info("Compiling LangGraph StateGraph agent using factory.create_agent...")
        agent = create_agent(
            model=llm,
            tools=[web_search, scrape_url]
        )
        logger.info("SUCCESS: LangGraph Agent compiled successfully.")
        
    except Exception as e:
        logger.error(f"FAIL: Graph compilation or LLM setup crashed. Reason: {e}")
        return

    # --- User Input ---
    print(format_separator("INPUT ACQUISITION"))
    user_input = input("Enter your research prompt: ")
    logger.info(f"Research prompt: '{user_input}'")

    # Preparing the graph input state
    input_state = {
        "messages": [HumanMessage(content=user_input)]
    }

    # --- Layer 3: LangGraph Stream Execution ---
    print(format_separator("LAYER 3: LANGGRAPH STREAM EXECUTION"))
    logger.info("Executing agent.stream() to trace state node transitions...")
    
    start_time = time.time()
    iteration = 0
    
    try:
        # Streaming the updates of the Compiled StateGraph
        for event in agent.stream(input_state):
            iteration += 1
            print(f"\n--- [LANGGRAPH EVENT {iteration}] ---")
            
            # Print the event keys to show which node of the graph ran
            node_names = list(event.keys())
            logger.info(f"Active node(s) executed: {node_names}")
            
            # Traverse each node's output in this step
            for node_name, node_output in event.items():
                print(f"[{node_name.upper()} NODE OUTPUT]")
                
                # Check messages modified/added by this node
                messages = node_output.get("messages", [])
                logger.info(f"Node '{node_name}' returned {len(messages)} message(s).")
                
                for msg in messages:
                    # Case A: Model inference output (AIMessage)
                    if isinstance(msg, AIMessage):
                        # Extract and print thinking process
                        reasoning = msg.additional_kwargs.get("reasoning_content")
                        if reasoning:
                            print(f"\n[MODEL REASONING (THINKING)]:\n{reasoning.strip()}\n")
                        else:
                            logger.info("No reasoning trace generated by model.")
                        
                        # Print tool calls requested
                        if msg.tool_calls:
                            print("\n[TOOL CALLS REQUESTED]:")
                            for tc in msg.tool_calls:
                                print(f"  - Tool: {tc['name']} (Args: {json.dumps(tc['args'])})")
                        
                        # Print plain text content (if any)
                        if msg.content:
                            print(f"\n[MODEL TEXT CONTENT]:\n{msg.content}")

                    # Case B: Tool execution outputs (ToolMessage)
                    elif isinstance(msg, ToolMessage):
                        logger.info(f"Tool execution completed for ID: {msg.tool_call_id}")
                        # Print a summary of the tool output to avoid flooding the terminal
                        content_str = str(msg.content)
                        logger.info(f"Tool result length: {len(content_str)} characters.")
                        print(f"\n[TOOL RESPONSE]:\n{content_str[:500]}...\n[TRUNCATED for readability]")
                        
                    else:
                        print(f"[UNKNOWN MESSAGE TYPE]: {type(msg)}")
                        print(msg)
                        
            # Delay slightly to prevent rapid consecutive hits to NVIDIA NIM
            time.sleep(1)
            
        elapsed = time.time() - start_time
        logger.info(f"LangGraph execution finished successfully in {elapsed:.2f} seconds.")
        
    except Exception as e:
        elapsed = time.time() - start_time
        logger.error(f"LangGraph execution CRASHED after {elapsed:.2f} seconds. Reason: {e}")

if __name__ == "__main__":
    run_diagnostic()
